# Generated by Django 4.2 on 2025-09-11 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('assunto', models.CharField(max_length=100, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('respondido', models.BooleanField(default=False, verbose_name='Respondido')),
            ],
            options={
                'verbose_name': 'Lead de Contato',
                'verbose_name_plural': 'Leads de Contato',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Financiamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('renda_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Renda Mensal')),
                ('profissao', models.CharField(max_length=100, verbose_name='Profissão')),
                ('entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Entrada')),
                ('carro_texto', models.CharField(blank=True, max_length=200, verbose_name='Carro (se não listado)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('aprovado', models.BooleanField(default=False, verbose_name='Pré-aprovado')),
                ('respondido', models.BooleanField(default=False, verbose_name='Respondido')),
                ('carro_interesse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carro', verbose_name='Carro de Interesse')),
            ],
            options={
                'verbose_name': 'Solicitação de Financiamento',
                'verbose_name_plural': 'Solicitações de Financiamento',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
