[build]
  publish = "staticfiles"
  command = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[build.environment]
  PYTHON_VERSION = "3.11"
  DJANGO_SETTINGS_MODULE = "regional_veiculos.settings"
  PYTHONPATH = "/opt/buildhome/repo"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  DEBUG = "False"
  ALLOWED_HOSTS = "*.netlify.app,*.netlify.com"
