[build]
  publish = "staticfiles"
  command = "python manage.py collectstatic --noinput"

[build.environment]
  PYTHON_VERSION = "3.13"
  DJANGO_SETTINGS_MODULE = "regional_veiculos.settings"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  DEBUG = "False"
  ALLOWED_HOSTS = "*.netlify.app,*.netlify.com"
