# Generated by Django 4.2 on 2025-09-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('fabricante', models.CharField(max_length=50, verbose_name='Fabricante')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('cor', models.CharField(max_length=30, verbose_name='Cor')),
                ('quilometragem', models.IntegerField(verbose_name='Quilometragem')),
                ('combustivel', models.CharField(default='Flex', max_length=20, verbose_name='Combustível')),
                ('cambio', models.CharField(default='Manual', max_length=20, verbose_name='Câmbio')),
                ('motor', models.CharField(max_length=30, verbose_name='Motor')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('condicao', models.CharField(choices=[('novo', 'Novo'), ('seminovo', 'Seminovo'), ('vendido', 'Vendido')], default='seminovo', max_length=10, verbose_name='Condição')),
                ('destaque', models.BooleanField(default=False, verbose_name='Carro em Destaque')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem_principal', models.ImageField(upload_to='carros/', verbose_name='Imagem Principal')),
                ('imagem_2', models.ImageField(blank=True, null=True, upload_to='carros/', verbose_name='Imagem 2')),
                ('imagem_3', models.ImageField(blank=True, null=True, upload_to='carros/', verbose_name='Imagem 3')),
                ('imagem_4', models.ImageField(blank=True, null=True, upload_to='carros/', verbose_name='Imagem 4')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['-criado_em'],
            },
        ),
    ]
