# Generated by Django 4.2 on 2025-09-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Marca')),
                ('logo', models.ImageField(upload_to='marcas/', verbose_name='Logo da Marca')),
                ('ativa', models.BooleanField(default=True, verbose_name='Marca Ativa')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
