# Generated by Django 4.2 on 2025-09-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Imagem')),
                ('tipo', models.CharField(choices=[('carro_flutuante', 'Carro Flutuante'), ('sobre_loja', 'Imagem da Loja (Sobre)'), ('banner_home', 'Banner Principal'), ('outras', 'Outras Imagens')], max_length=20, verbose_name='Tipo da Imagem')),
                ('imagem', models.ImageField(upload_to='site_images/', verbose_name='Imagem')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Imagem do Site',
                'verbose_name_plural': 'Imagens do Site',
                'ordering': ['tipo', 'ordem'],
            },
        ),
    ]
